# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlExp', '0002_auto_20160803_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='exp',
            field=models.CharField(default='', max_length=200),
        ),
    ]
