# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlExp', '0003_input_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='waytime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='input',
            name='wayurl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
